### ISSUE TITLE
git call failed

### ISSUE THREAD

**Issue by Xstar99** [Kuri-su/KBlog#29]
[Call Trace]
./stack.sh:723:git_clone
/opt/stack/devstack/functions-common:537:git_timed
/opt/stack/devstack/functions-common:604:die
[ERROR] /opt/stack/devstack/functions-common:604 git call failed: [git clone git://git.openstack.org/openstack/requirements.git /opt/stack/requirements]
Error on exit
World dumping... see /opt/stack/logs/worlddump-2022-04-23-030042.txt for details
ebtables v1.8.7 (nf_tables): table `broute' is incompatible, use 'nft' tool.

报错提示，已经全局代理socks5，为什么还是git有问题呢

**Comment by Kuri-su** [comment]
看下这里 /opt/stack/logs/worlddump-2022-04-23-030042.txt 的日志
