### ISSUE TITLE
oh-my-zsh-git-alias.md

### ISSUE THREAD

**Issue by xiebruce** [Kuri-su/KBlog#30]
请问[这些alias](https://kuricat.com/gist/oh-my-zsh-git-alias-h5t8x)是在oh-my-zsh的哪个文件中定义的？我找了一遍都没找到，有一个git.zsh：`~/.oh-my-zsh/lib/git.zsh`，但我在里面搜索了一下，根本就没有alias这些命令，比如：gcmsg

**Comment by Kuri-su** [comment]
~/.oh-my-zsh/plugins/git/git.plugin.zsh

Bruce ***@***.***> 于2022年5月19日周四 17:53写道：

**Comment by xiebruce** [comment]
> ~/.oh-my-zsh/plugins/git/git.plugin.zsh

啊，感谢感谢，我竟然就漏了这个🤣 话说你博客为啥不直接弄个valine插件，这样就了可以在博客那边直接评论了

**Comment by Kuri-su** [comment]
想人为设置门槛...要跳转一道并发个 Issue.....过滤掉一些不必要评论.....毕竟中文环境你知道的.....


Bruce ***@***.***> 于2022年5月20日周五 13:47写道：

**Comment by xiebruce** [comment]
好吧，原来如此，也有道理

**Comment by Kuri-su** [comment]
/close

Bruce ***@***.***> 于2022年5月21日周六 15:35写道：
